# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

filegroup(
    name = "info_plists",
    testonly = True,
    srcs = [
        "spoor_runtime_xctoolchain_info.plist",
        "unknown_xctoolchain_version.plist",
    ],
    visibility = ["//toolchain/xcode:__subpackages__"],
)
