# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

site_name: Spoor
repo_url: https://github.com/microsoft/spoor
copyright: Copyright &copy; Microsoft Corporation
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    logo: fontawesome/solid/paw
    repo: fontawesome/brands/git-alt
  features:
    - navigation.instant
    - navigation.tabs
markdown_extensions:
 - pymdownx.highlight
 - pymdownx.inlinehilite
 - pymdownx.superfences
 - pymdownx.snippets
