# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

site_name: Spoor
site_url: https://www.spoor.dev
repo_url: https://github.com/microsoft/spoor
repo_name: microsoft/spoor
site_description: Spoor documentation and reference.
site_author: Microsoft Corporation
copyright: Copyright &copy; Microsoft Corporation
theme:
  name: material
  language: en
  palette:
    scheme: default
    primary: blue grey
  icon:
    logo: fontawesome/solid/paw
    repo: fontawesome/brands/git-alt
  features:
  - navigation.instant
  - navigation.tabs
  - navigation.top
markdown_extensions:
- admonition
- attr_list
- md_in_html
- pymdownx.arithmatex:
    generic: true
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true 
nav:
- Home: index.md
- Get Started:
  - Overview: get-started/index.md
  - Xcode Toolchain: get-started/xcode-toolchain.md
- Reference:
  - Overview: reference/index.md
  - Instrumentation:
    - Overview: reference/instrumentation/index.md
    - Configuration: reference/instrumentation/configuration.md
  - Runtime:
    - Overview: reference/runtime/index.md
    - Configuration: reference/runtime/configuration.md
  - Postprocessing:
    - Overview: reference/postprocessing/index.md
- Tutorials:
  - Overview: tutorials/index.md
  - Fibonacci: tutorials/fibonacci.md
  - Wikipedia iOS: tutorials/wikipedia-ios.md
- Contributing:
  - Overview: contributing/index.md
  - Development Setup: contributing/development-setup.md
  - Style Guide: contributing/style-guide.md
  - Code of Conduct: contributing/code-of-conduct.md
  - Security: contributing/security.md
  - License: contributing/license.md
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/microsoft/spoor
extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
