#ifndef SPOOR_TOOLCHAIN_COMPILATION_DATABASE_CONCATENATE_COMPILE_COMMANDS_H_
#define SPOOR_TOOLCHAIN_COMPILATION_DATABASE_CONCATENATE_COMPILE_COMMANDS_H_

#include <gflags/gflags.h>

#include <string>

#include "util/flags.h"

namespace toolchain::compilation_database {

const char* const kConcatenateCompileCommandsVersion = "1.0.0";
const char* const kUsage =
    "Concatenate compile command intermediate protocol buffers generated by "
    "the `extract_compile_command` action listener, inject the execution "
    "directory, and output the generated JSON compilation database. The "
    "intermediate file names are read from stdin.";

DEFINE_string(  // NOLINT
    compile_command_directory, "", "Directory for each commpile command.");

DEFINE_validator(  // NOLINT
    compile_command_directory, &util::flags::ValidateInputFilePath);

DEFINE_string(  // NOLINT
    output_compilation_database, "",
    "Path to the output compile_commands.json file.");

DEFINE_validator(  // NOLINT
    output_compilation_database, &util::flags::ValidateOutputFilePath);

}  // namespace toolchain::compilation_database

#endif
