# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

filegroup(
    name = "minimal_swift_ios_app",
    testonly = True,
    srcs = glob(["**/*"]),
    visibility = ["//toolchain/xcode:__subpackages__"],
)
