# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

filegroup(
    name = "test_data",
    testonly = True,
    srcs = ["fib.cc"],
    visibility = ["//spoor:__subpackages__"],
)
