jobs:
- job: test
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-18.04'
      mac:
        imageName: 'macos-10.15'
      windows:
        imageName: 'windows-2019'
  pool:
    vmImage: $(imageName)
  steps:
    - script: echo "Test"
