# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

trigger:
- master

# TODO(#58): Support Linux in CI and reintroduce UBSAN (Linux only).

jobs:
- job: build_and_test
  timeoutInMinutes: 75
  strategy:
    matrix:
      mac:
        imageName: 'macos-10.15'
  pool:
    vmImage: $(imageName)
  steps:
  - template: ./templates/install-common.yml
  - script: bazel build //...
    displayName: Build
  - script: bazel test //...
    displayName: Test
  - script: ./toolchain/benchmark/run_benchmarks.sh
    displayName: Benchmark
- job: build_and_test_llvm
  timeoutInMinutes: 75
  strategy:
    matrix:
      mac:
        imageName: 'macos-10.15'
  pool:
    vmImage: $(imageName)
  steps:
  - template: ./templates/install-common.yml
  - script: |
      bazel build //... --crosstool_top=//toolchain/crosstool:llvm_toolchain
    displayName: Build (LLVM toolchain)
  - script: |
      bazel test //... --crosstool_top=//toolchain/crosstool:llvm_toolchain
    displayName: Test (LLVM toolchain)
- job: address_sanitizer
  timeoutInMinutes: 75
  strategy:
    matrix:
      mac:
        imageName: 'macos-10.15'
  pool:
    vmImage: $(imageName)
  steps:
  - template: ./templates/install-common.yml
  - script: bazel test --config=asan $(bazel query 'kind(cc_.*, tests(//...))')
    displayName: Address sanitizer
- job: thread_sanitizer
  timeoutInMinutes: 75
  strategy:
    matrix:
      mac:
        imageName: 'macos-10.15'
  pool:
    vmImage: $(imageName)
  steps:
  - template: ./templates/install-common.yml
  - script: bazel test --config=tsan $(bazel query 'kind(cc_.*, tests(//...))')
    displayName: Thread sanitizer
- job: style_and_lint
  timeoutInMinutes: 75
  strategy:
    matrix:
      mac:
        imageName: 'macos-10.15'
  pool:
    vmImage: $(imageName)
  steps:
  - template: ./templates/install-common.yml
  - script: |
      ./toolchain/copyright_header/add_copyright_header.sh
      git diff --exit-code
    displayName: Copyright header
  - script: |
      bazel build //... \
          --aspects toolchain/style/style.bzl%format \
          --output_groups=report \
          --keep_going
      bazel run //toolchain/style:buildifier
      git diff --exit-code
    displayName: Format
  - script: |
      bazel build //... \
          --crosstool_top=//toolchain/crosstool:llvm_toolchain \
          --aspects toolchain/style/style.bzl%lint \
          --output_groups=report \
          --keep_going
    displayName: Lint
