# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

trigger:
- master

jobs:
- job: build_and_test
  strategy:
    matrix:
      # TODO(#58): Support Linux in CI and reintroduce UBSAN (Linux only).
      mac:
        imageName: 'macos-10.15'
  pool:
    vmImage: $(imageName)
  steps:
  - template: ./templates/install-common.yml
  - script: bazel build //...
    displayName: Build
  - script: bazel test //...
    displayName: Test
  - script: ./toolchain/benchmark/run_benchmarks.sh
    displayName: Benchmark
- job: address_sanitizer
  strategy:
    matrix:
      mac:
        imageName: 'macos-10.15'
  pool:
    vmImage: $(imageName)
  steps:
  - template: ./templates/install-common.yml
  - script: bazel test --config=asan $(bazel query 'kind(cc_.*, tests(//...))')
    displayName: Address sanitizer
- job: thread_sanitizer
  strategy:
    matrix:
      mac:
        imageName: 'macos-10.15'
  pool:
    vmImage: $(imageName)
  steps:
  - template: ./templates/install-common.yml
  - script: bazel test --config=tsan $(bazel query 'kind(cc_.*, tests(//...))')
    displayName: Thread sanitizer
- job: style_and_lint
  strategy:
    matrix:
      mac:
        imageName: 'macos-10.15'
  pool:
    vmImage: $(imageName)
  steps:
  - template: ./templates/install-common.yml
  - script: |
      ./toolchain/copyright_header/add_copyright_header.sh
      git diff --exit-code
    displayName: Copyright header
  - script: |
      bazel build //... --aspects toolchain/style/style.bzl%clang_format \
          --output_groups=report
      git diff --exit-code
    displayName: Clang Format
  - script: |
      bazel run //toolchain/style:buildifier
      git diff --exit-code
    displayName: Buildifier
  - script: |
      bazel build //... --aspects toolchain/style/style.bzl%clang_tidy \
          --output_groups=report --keep_going
    displayName: Clang Tidy
