jobs:
- job: build_and_test
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-20.04'
      mac:
        imageName: 'macos-10.15'
  pool:
    vmImage: $(imageName)
  steps:
  - template: ./templates/install-common.yml
  - script: bazel build //...
    displayName: Build
  - script: bazel test //...
    displayName: Test
- job: style_and_lint
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - template: ./templates/install-common.yml
  - script: sudo apt-get install clang-format clang-tidy
    displayName: Install Clang Format and Clang Tidy
  - script: |
      ./toolchain/style/clang_format.sh
      git diff --exit-code
    displayName: Clang Format
  - script: |
      bazel run //toolchain/style:buildifier
      git diff --exit-code
    displayName: Buildifier
  - script: ./toolchain/style/clang_tidy.sh
    displayName: Clang Tidy
    env:
      AZURE_PIPELINES_OS: $(Agent.OS)
