# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

filegroup(
    name = "build_intermediates",
    testonly = True,
    srcs = [
        "modified-module-OutputFileMap.json",
        "module-OutputFileMap.json",
    ],
    visibility = ["//spoor/toolchains/xcode:__pkg__"],
)
