# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

filegroup(
    name = "minimal_objc_ios_app",
    testonly = True,
    srcs = glob(["**/*"]),
    visibility = ["//spoor/toolchains/xcode:__pkg__"],
)
