filegroup(
    name = "test_data",
    srcs = [
       "fib.ll",
       "fib_debug.ll",
       "fib_instrumented.ll",
       "fib_instrumented_initialized.ll",
       "fib_instrumented_initialized_enabled.ll",
       "fib_only_main_instrumented.ll",
    ],
    visibility = ["//visibility:public"],
)

