# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

filegroup(
    name = "test_data",
    srcs = [
        "fib.ll",
        "fib_debug_c.ll",
        "fib_debug_cpp.ll",
        "fib_debug_objc.ll",
        "fib_debug_swift.ll",
        "fib_instrumented.ll",
        "fib_instrumented_initialized.ll",
        "fib_instrumented_initialized_enabled.ll",
        "fib_only_main_instrumented.ll",
    ],
    visibility = ["//visibility:public"],
)
