filegroup(
    name = "test_data",
    srcs = [
        "fib.ll",
        "fib_debug_cpp.ll",
        "fib_debug_swift.ll",
        "fib_debug_swift_patched.ll",  # TODO
        "fib_instrumented.ll",
        "fib_instrumented_initialized.ll",
        "fib_instrumented_initialized_enabled.ll",
        "fib_only_main_instrumented.ll",
    ],
    visibility = ["//visibility:public"],
)
