# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

constraint_setting(name = "os")
constraint_value(
    name = "linux",
    constraint_setting = ":os",
)

constraint_value(
    name = "mac",
    constraint_setting = ":os",
)

platform(
    name = "linux_x86_64",
    constraint_values = [
    ],
)

platform(
    name = "linux_arm64",
    constraint_values = [
    ],
)

platform(
    name = "macos_x86_64",
    constraint_values = [
    ],
)

platform(
    name = "macos_arm64",
    constraint_values = [
    ],
)

platform(
    name = "ios_arm64",
    constraint_values = [
    ],
)

platform(
    name = "windows_x86_64",
    constraint_values = [
    ],
)

platform(
    name = "windows_arm64",
    constraint_values = [
    ],
)
